/**
 * Register the service worker generated by `vite-plugin-pwa` (`vite.config.ts`'s `generateSW`
 * config). Web/PWA only — a Capacitor build must never call this (research/08 §1.2: WKWebView on
 * `capacitor://localhost` does not run service workers; assets are bundled instead). Since
 * `platform.name` only ever reports `"web"` today, there is nothing to branch on yet — the
 * Capacitor entry point (when it exists) should skip this call entirely rather than have this
 * function grow a runtime check.
 */
import { registerSW } from "virtual:pwa-register";

/** How often to ask the server whether a newer build exists, while the app stays open. */
const UPDATE_CHECK_MS = 60 * 60 * 1000;

export function registerServiceWorker(): void {
  if (!("serviceWorker" in navigator)) return;

  // No `onNeedRefresh`: under `registerType: "autoUpdate"` it is never called. What applies an
  // update is the worker itself (`skipWaiting` + `clientsClaim`, `vite.config.ts`) and then
  // `registerSW`, which reloads the page when a newer worker activates. There used to be an
  // `onNeedRefresh` here that "applied" the update — dead code, which is how B-532 (the new worker
  // waiting forever) hid behind B-20's fix.
  //
  // That reload is safe with respect to unsaved text: a pending edit is flushed on `pagehide` and
  // `visibilitychange` (`editor/BlockTree.tsx`), both of which fire before it.
  registerSW({
    immediate: true,
    onOfflineReady() {
      console.info("[nooklet] ready to work offline.");
    },
    onRegisteredSW(_url, registration) {
      // A service worker only checks for a new version on navigation, so a long-lived tab would
      // otherwise never notice a deploy.
      if (registration) setInterval(() => void registration.update(), UPDATE_CHECK_MS);
    },
  });
}
