/**
 * Register the service worker generated by `vite-plugin-pwa` (`vite.config.ts`'s `generateSW`
 * config). Web/PWA only — a Capacitor build must never call this (research/08 §1.2: WKWebView on
 * `capacitor://localhost` does not run service workers; assets are bundled instead). Since
 * `platform.name` only ever reports `"web"` today, there is nothing to branch on yet — the
 * Capacitor entry point (when it exists) should skip this call entirely rather than have this
 * function grow a runtime check.
 */
import { registerSW } from "virtual:pwa-register";

export function registerServiceWorker(): void {
  if (!("serviceWorker" in navigator)) return;
  registerSW({
    immediate: true,
    onNeedRefresh() {
      // TODO(views): surface a real "update available" affordance instead of a console log.
      console.info("[nooklet] an update is available; reload to apply it.");
    },
    onOfflineReady() {
      console.info("[nooklet] ready to work offline.");
    },
  });
}
