apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nooklet.fullname" . }}
  labels:
    {{- include "nooklet.labels" . | nindent 4 }}
  {{- if .Values.persistence.keepOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
