{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nooklet.fullname" . }}
  labels:
    {{- include "nooklet.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-token: {{ required "rootToken (or existingSecret) is required" .Values.rootToken | quote }}
{{- end }}
